#!/bin/bash

# ACCESS PAL - Start and Test Script
# This script starts the server and provides testing instructions

echo "🚀 ACCESS PAL - Push Notification Fix Applied!"
echo "=============================================="
echo ""

# Check if VAPID keys are configured
echo "📋 Checking VAPID Keys Configuration..."
cd /Users/mediad/access-pal/server
node -e "require('dotenv').config(); if (process.env.VAPID_PUBLIC_KEY && process.env.VAPID_PRIVATE_KEY && process.env.VAPID_SUBJECT) { console.log('✅ All VAPID keys are configured correctly!'); } else { console.log('❌ ERROR: VAPID keys are missing!'); process.exit(1); }"

if [ $? -ne 0 ]; then
    echo ""
    echo "❌ VAPID keys are not configured. Please check server/.env file."
    exit 1
fi

echo ""
echo "=============================================="
echo "🎯 PUSH NOTIFICATION FIX SUMMARY"
echo "=============================================="
echo ""
echo "✅ Fixed: Added VAPID keys to server/.env"
echo "✅ Fixed: Push notification service configured"
echo "✅ Verified: All code components are in place"
echo ""
echo "=============================================="
echo "📝 TESTING INSTRUCTIONS"
echo "=============================================="
echo ""
echo "1. START THE SERVER:"
echo "   cd /Users/mediad/access-pal/server"
echo "   npm run dev"
echo ""
echo "2. START THE CLIENT (in new terminal):"
echo "   cd /Users/mediad/access-pal/client"
echo "   npm run dev"
echo ""
echo "3. TEST PUSH NOTIFICATIONS:"
echo "   a) Open http://localhost:3000/dashboard in browser"
echo "   b) Login with your credentials"
echo "   c) Grant notification permission when prompted"
echo "   d) Wait for console message: '✅ Auto-subscribed to push notifications'"
echo "   e) Close the dashboard tab/window"
echo "   f) Open http://localhost:3000/visit/YOUR_QR_CODE_ID in another tab"
echo "   g) Click 'Start Video Call'"
echo "   h) Check for push notification on your device!"
echo ""
echo "4. CHECK SERVER LOGS:"
echo "   You should see:"
echo "   - 🔔🔔🔔 VISITOR-ALERT EVENT RECEIVED"
echo "   - 📱 Sending push notification..."
echo "   - ✅ Push notification sent successfully"
echo ""
echo "=============================================="
echo "🐛 TROUBLESHOOTING"
echo "=============================================="
echo ""
echo "If notification doesn't appear:"
echo "  • Check browser console for errors"
echo "  • Verify notification permission is granted"
echo "  • Check server logs for push errors"
echo "  • Try hard refresh (Cmd+Shift+R)"
echo "  • Clear browser data and try again"
echo ""
echo "For production testing:"
echo "  • Production already has VAPID keys in render.yaml"
echo "  • Deploy and test on actual devices"
echo "  • Check Render logs for confirmation"
echo ""
echo "=============================================="
echo "✅ READY TO START!"
echo "=============================================="
echo ""
echo "Run these commands in separate terminals:"
echo ""
echo "Terminal 1 (Server):"
echo "  cd /Users/mediad/access-pal/server && npm run dev"
echo ""
echo "Terminal 2 (Client):"
echo "  cd /Users/mediad/access-pal/client && npm run dev"
echo ""
